const bank_name = [
    "State Bank of India (SBI)",
    "Bank of Baroda (BoB)",
    "Punjab National Bank (PNB)",
    "Canara Bank",
    "Union Bank of India",
    "Bank of India",
    "Indian Bank",
    "Central Bank of India",
    "Indian Overseas Bank",
    "UCO Bank",
    "Bank of Maharashtra",
    "Punjab & Sind Bank",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "IndusInd Bank",
    "Yes Bank",
    "IDFC FIRST Bank",
    "Federal Bank",
    "South Indian Bank",
    "RBL Bank",
    "Bandhan Bank",
    "DCB Bank",
    "Karur Vysya Bank",
    "City Union Bank",
    "Jammu & Kashmir Bank",
    "AU Small Finance Bank",
    "Equitas Small Finance Bank",
    "Ujjivan Small Finance Bank",
    "Jana Small Finance Bank",
    "Suryoday Small Finance Bank",
    "ESAF Small Finance Bank",
    "Fincare Small Finance Bank",
    "North East Small Finance Bank",
    "Utkarsh Small Finance Bank",
    "Capital Small Finance Bank",
    "Shivalik Small Finance Bank",
  ];
  
  bank_name.sort()
  
  export default bank_name